FinalSEMVC/Controllers/BillsController.cs
using System;
using System.Collections.Generic;
using System.Data;
using System.Data.Entity;
using System.Linq;
using System.Net;
using System.Web;
using System.Web.Mvc;
using FinalSEMVC.Models;

namespace FinalSEMVC.Controllers
{
    public class BillsController : Controller
    {
        private Shop1Entities db = new Shop1Entities();

        // GET: Bills
        public ActionResult Index()
        {
            return View(db.Bills.ToList());
        }

        // GET: Bills/Details/5
        public ActionResult Details(string id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            Bill bill = db.Bills.Find(id);
            if (bill == null)
            {
                return HttpNotFound();
            }
            return View(bill);
        }

        // GET: Bills/Create
        public ActionResult Create()
        {
            return View();
        }

        // POST: Bills/Create
        // To protect from overposting attacks, enable the specific properties you want to bind to, for 
        // more details see https://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Create([Bind(Include = "BillID,AgentID,Price,Deliver,Pay")] Bill bill)
        {
            if (ModelState.IsValid)
            {
                db.Bills.Add(bill);
                db.SaveChanges();
                return RedirectToAction("Index");
            }

            return View(bill);
        }

        // GET: Bills/Edit/5
        public ActionResult Edit(string id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            Bill bill = db.Bills.Find(id);
            if (bill == null)
            {
                return HttpNotFound();
            }
            return View(bill);
        }

        // POST: Bills/Edit/5
        // To protect from overposting attacks, enable the specific properties you want to bind to, for 
        // more details see https://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Edit([Bind(Include = "BillID,AgentID,Price,Deliver,Pay")] Bill bill)
        {
            if (ModelState.IsValid)
            {
                db.Entry(bill).State = EntityState.Modified;
                db.SaveChanges();
                return RedirectToAction("Index");
            }
            return View(bill);
        }

        // GET: Bills/Delete/5
        public ActionResult Delete(string id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            Bill bill = db.Bills.Find(id);
            if (bill == null)
            {
                return HttpNotFound();
            }
            return View(bill);
        }

        // POST: Bills/Delete/5
        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        public ActionResult DeleteConfirmed(string id)
        {
            Bill bill = db.Bills.Find(id);
            db.Bills.Remove(bill);
            db.SaveChanges();
            return RedirectToAction("Index");
        }

        protected override void Dispose(bool disposing)
        {
            if (disposing)
            {
                db.Dispose();
            }
            base.Dispose(disposing);
        }
    }
}

FinalSEMVC/Controllers/HomeController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;

namespace FinalSEMVC.Controllers
{
    public class HomeController : Controller
    {
        public ActionResult Index()
        {
            return View();
        }

        public ActionResult About()
        {
            ViewBag.Message = "Your application description page.";

            return View();
        }

        public ActionResult Contact()
        {
            ViewBag.Message = "Your contact page.";

            return View();
        }

        public ActionResult Items()
        {
            ViewBag.Message = "Your contact page.";

            return View();
        }

        public ActionResult note()
        {
            ViewBag.Message = "Your contact page.";

            return View();
        }
    }
}

FinalSEMVC/Controllers/ProductsController.cs
using System;
using System.Collections.Generic;
using System.Data;
using System.Data.Entity;
using System.Linq;
using System.Net;
using System.Web;
using System.Web.Mvc;
using FinalSEMVC.Models;

namespace FinalSEMVC.Controllers
{
    public class ProductsController : Controller
    {
        private Shop1Entities db = new Shop1Entities();

        // GET: Products
        public ActionResult Index()
        {
            return View(db.Products.ToList());
        }

        // GET: Products/Details/5
        public ActionResult Details(string id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            Product product = db.Products.Find(id);
            if (product == null)
            {
                return HttpNotFound();
            }
            return View(product);
        }

        // GET: Products/Create
        public ActionResult Create()
        {
            return View();
        }

        // POST: Products/Create
        // To protect from overposting attacks, enable the specific properties you want to bind to, for 
        // more details see https://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Create([Bind(Include = "ProductID,ProductName,Price")] Product product)
        {
            if (ModelState.IsValid)
            {
                db.Products.Add(product);
                db.SaveChanges();
                return RedirectToAction("Index");
            }

            return View(product);
        }

        // GET: Products/Edit/5
        public ActionResult Edit(string id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            Product product = db.Products.Find(id);
            if (product == null)
            {
                return HttpNotFound();
            }
            return View(product);
        }

        // POST: Products/Edit/5
        // To protect from overposting attacks, enable the specific properties you want to bind to, for 
        // more details see https://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Edit([Bind(Include = "ProductID,ProductName,Price")] Product product)
        {
            if (ModelState.IsValid)
            {
                db.Entry(product).State = EntityState.Modified;
                db.SaveChanges();
                return RedirectToAction("Index");
            }
            return View(product);
        }

        // GET: Products/Delete/5
        public ActionResult Delete(string id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            Product product = db.Products.Find(id);
            if (product == null)
            {
                return HttpNotFound();
            }
            return View(product);
        }

        // POST: Products/Delete/5
        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        public ActionResult DeleteConfirmed(string id)
        {
            Product product = db.Products.Find(id);
            db.Products.Remove(product);
            db.SaveChanges();
            return RedirectToAction("Index");
        }

        protected override void Dispose(bool disposing)
        {
            if (disposing)
            {
                db.Dispose();
            }
            base.Dispose(disposing);
        }
    }
}

FinalSEMVC/Views/Home/About.cshtml
@{
    ViewBag.Title = "About";
}
<main aria-labelledby="title">
    <h2 id="title">@ViewBag.Title.</h2>
    <p>This website has been created by Mr.Phuc and Ms.Long to serve the customer </p>
</main>

FinalSEMVC/Views/Home/Contact.cshtml
@{
    ViewBag.Title = "Contact";
}
<main aria-labelledby="title">
    <h2 id="title">@ViewBag.Title.</h2>


    <address>
        Vietnam - Ho Chi Minh City<br />
        Binh Tan x Binh Thanh<br />
        <abbr title="Phone">P:</abbr>
        19001560
    </address>

    <address>
        <strong>Support:</strong>   <a href="https://www.facebook.com/profile.php?id=100074498322280">521K0165@student.tdtu.edu.vn</a><br />
        <strong>Marketing:</strong> <a href="https://www.facebook.com/tienphucnguyenn">521K0114@student.tdtu.edu.vn</a>
    </address>
</main>

FinalSEMVC/Views/Home/Index.cshtml
@{
    ViewBag.Title = "Home Page";
}

<main>
            <section class="row" aria-labelledby="aspnetTitle">
                <h1 id="title" class="title">Mobile Phone Product Thingy</h1>
                <p class="lead">This is a fresh brand new Company. Expect the unexpected!</p>
                
            </section>

            <div class="row">
                <section class="col-md-4" aria-labelledby="gettingStartedTitle">
                    <h2 id="gettingStartedTitle" class="header"></h2>
                    <p class="p">
                       
                    </p>
                    <p><a class="btn btn-outline-dark" href="https://cellphones.com.vn/dich-vu-thanh-toan-hoa-don">Payment &raquo;</a></p>
                </section>
                <section class="col-md-4" aria-labelledby="librariesTitle">
                    <h2 id="librariesTitle" class="header"></h2>
                    <p class="p"></p>
                    <p><a class="btn btn-outline-dark" href="https://cellphones.com.vn/mobile.html">Company Web page &raquo;</a></p>
                </section>
                <section class="col-md-4" aria-labelledby="hostingTitle">
                    <h2 id="hostingTitle" class="header"></h2>
                    <p class="p"></p>
                    <p><a class="btn btn-outline-dark" href="https://cellphones.com.vn/dich-vu-khach-hang-doanh-nghiep">Support / Help &raquo;</a></p>
                </section>
            </div>
</main>

<style>
    .col-md-4 {
        background: linear-gradient(to bottom, #034001, #d9a282);
    }

    .header {
        color: white;
    }

    .row {
        background: linear-gradient(to bottom, #027368, #034001);
    }

    .lead {
        color: #d9a282;
        font-weight: bold;
    }

    .title {
        color: #d9a282;
    }

    .p{
        color: white;
    }
</style>

FinalSEMVC/Views/Home/Items.cshtml
@{
    ViewBag.Title = "Items";
}

<h1>
    Site for checking Items in Warehouse
</h1>

<div>
    <div>
        @Html.ActionLink("Warehouse", "Index", "Products")
    </div>
</div>

FinalSEMVC/Views/Home/note.cshtml
@{
    ViewBag.Title = "note";
}
<h1>
    Site for checking Delivery Status 
</h1>

<div>
    <div>
        @Html.ActionLink("Delivery Note", "Index", "Bills")
    </div>
</div>